name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Java 21 einrichten
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Gradle Wrapper ausführbar machen
        run: chmod +x ./gradlew

      - name: Projekt bauen
        run: ./gradlew build

      - name: Tests ausführen
        run: ./gradlew test
